/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OlliComponent {
        "first": string;
        "last": string;
    }
}
declare global {
    interface HTMLOlliComponentElement extends Components.OlliComponent, HTMLStencilElement {
    }
    var HTMLOlliComponentElement: {
        prototype: HTMLOlliComponentElement;
        new (): HTMLOlliComponentElement;
    };
    interface HTMLElementTagNameMap {
        "olli-component": HTMLOlliComponentElement;
    }
}
declare namespace LocalJSX {
    interface OlliComponent {
        "first"?: string;
        "last"?: string;
    }
    interface IntrinsicElements {
        "olli-component": OlliComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "olli-component": LocalJSX.OlliComponent & JSXBase.HTMLAttributes<HTMLOlliComponentElement>;
        }
    }
}
